export const mockRooms = [
  {
    id: "1",
    roomName: "Room 101",
    building: "Irving K. Barber Learning Centre",
    source: "UBC Library",
    capacity: 4,
    availableNow: true,
    nextAvailableSlot: null,
    bookingUrl: "https://example.com",
    lastUpdated: "2 mins ago",
  },
  {
    id: "2",
    roomName: "Study Room 4201",
    building: "AMS Nest",
    source: "AMS",
    capacity: 6,
    availableNow: false,
    nextAvailableSlot: "3:00 PM",
    bookingUrl: "https://example.com",
    lastUpdated: "1 min ago",
  },
  {
    id: "3",
    roomName: "Group Study Room 204",
    building: "Koerner Library",
    source: "UBC Library",
    capacity: 5,
    availableNow: true,
    nextAvailableSlot: null,
    bookingUrl: "https://example.com",
    lastUpdated: "3 mins ago",
  },
];